### ISSUE TITLE
Farmland list view is not showing

### ISSUE THREAD

**Issue by AldwinVergara** [radical-doubting/anikultura-backend#170]
### Description

A bug regarding null "farmschool_name" property in the farmland list layout displays an error.

![image](https://user-images.githubusercontent.com/70194069/195592724-41734008-fcc9-4cf7-90c9-a964b221bbfc.png)

### Reproduction steps

1. Go to Farmland management page
2. See bug

### Expected behavior

The list of all registered farmlands should appear.

### Affected browsers (if applicable)

Firefox, Chrome, Safari, Microsoft Edge

**Comment by jg-rivera** [comment]
Please verify, @AldwinVergara. Thanks!

**Comment by AldwinVergara** [comment]
It is now working. Thank you @jg-rivera !
