### ISSUE TITLE
Editing a farmer report prompts error

### ISSUE THREAD

**Issue by AldwinVergara** [radical-doubting/anikultura-backend#171]
### Description

Upon clicking a farmer report in the farmer report management page, it displays a null error exception on "farmschool_name" variable.
![Uploading image.png…]()

### Reproduction steps

1. Go to farmer report management page
2. Click an existing farmer report
3. See bug

### Expected behavior

It should redirect to the edit screen of the farmer report and should display the existing report's details.

### Affected browsers (if applicable)

Chrome

**Comment by jg-rivera** [comment]
Please verify, @AldwinVergara. Thanks!

**Comment by AldwinVergara** [comment]
The bug is now fixed! Thank you @jg-rivera!
