### ISSUE TITLE
Optimize 'update password' layout or section in admin profile

### ISSUE THREAD

**Issue by AldwinVergara** [radical-doubting/anikultura-backend#172]
### Describe the solution you'd like

-Remove the password field in the Profile Information section
-Allow editing other admin profile details without requiring inputs in password field and change the password
-Changing password should not be required (?) or be optional (it affects saving updates regarding other admin profile details)

### Describe alternatives you've considered

-There's a different page for updating a password

**Comment by jg-rivera** [comment]
Please verify, @AldwinVergara. Thanks!

**Comment by AldwinVergara** [comment]
Works fine! Thank you @jg-rivera !
