### ISSUE TITLE
Visual Bug Where There are Two Hide Password Button Shown in the Login Screen

### ISSUE THREAD

**Issue by yucabeltran** [radical-doubting/anikultura-backend#179]
### Description

There are two hide password button shown in the login screen.

![image](https://user-images.githubusercontent.com/69507787/195765010-80b257f1-f1a5-4091-91c5-61e3e0a3a7fd.png)

### Reproduction steps

1. Login at https://qa-anikultura-md.herokuapp.com/.
2. Input email and password.

### Expected behavior

There should only be 1 button to hide and see password.

**Comment by jg-rivera** [comment]
This bug is dependent on the browser and extensions (e.g. password managers) used. The bug does not appear on Google Chrome without password manager extensions. Users of LastPass Chrome extension observed that the hide password icon is glitched too.
