### ISSUE TITLE
Add English Translation to the Screens Described in this Issue

### ISSUE THREAD

**Issue by yucabeltran** [radical-doubting/anikultura-backend#190]
### Description

Some screens aren't translated yet.

1. Profile Section
![image](https://user-images.githubusercontent.com/69507787/196871140-0ef43511-655a-440a-ab48-5fa6b22cb82a.png)

2. Notification
![image](https://user-images.githubusercontent.com/69507787/196871470-34c4626e-ec5c-484e-b393-a4d92839b0b4.png)

3. Search Bar
![image](https://user-images.githubusercontent.com/69507787/196871545-3e5b12c4-8e87-4f20-a8cf-3b55909cdda9.png)

### Reproduction steps

1. Login as Admin in Admin Dashboard.
2. Go to the screens mentioned above.

### Expected behavior

All translatable words should be translated.

**Comment by AldwinVergara** [comment]
Created a fix for this. You could check the 'updated_translations' branch.

**Comment by jg-rivera** [comment]
The reported translation issues have been fixed.
