### ISSUE TITLE
A Prompt 'Farmer Does Not Belong to a Batch' Shows up Upon Saving a Farmland

### ISSUE THREAD

**Issue by yucabeltran** [radical-doubting/anikultura-backend#199]
### Description

A prompt shows up while saving a farmland.
![image](https://user-images.githubusercontent.com/69507787/197678998-4769e861-2fe3-4957-91df-b11ba1ed7abe.png)

### Reproduction steps

1. Go to farmland management.

2. Click Pietro Farmland.
![image](https://user-images.githubusercontent.com/69507787/197678893-97c4cf07-2089-416d-9d38-d6508997370f.png)

3. Click Save.
![image](https://user-images.githubusercontent.com/69507787/197678927-acb9b929-1d96-4462-bae2-37fb2cc56687.png)

### Expected behavior

This prompt is only appropriate in farmer management.

**Comment by jg-rivera** [comment]
Please verify whether the farmer in the farmland actually belongs to the batch.
